### ISSUE TITLE
Add requirements

### ISSUE THREAD

**Issue by ibrahimalab** [Ibrahim-Ola/airbnb-dashboard-python#1]
Hey @Ibrahim-Ola,

I saw you spelt out the required libraries explicitly. Could you use a requirement file instead?

**Comment by Ibrahim-Ola** [comment]
Hey @ibrahimalab,

Thank you for raising this! I'm addressing that right away!

**Comment by Ibrahim-Ola** [comment]
I just added it.

Thanks again!
